# NOTE: Generated By HttpRunner v4.3.5
# FROM: .\testcase\bdfy.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseBdfy(HttpRunner):

    config = Config("testcase description").base_url("https://fanyi.baidu.com")

    teststeps = [
        Step(
            RunRequest("/ait/config/cms/list")
            .get("/ait/config/cms/list")
            .with_params(
                **{
                    "date": "1743576063699?_=1743576063699",
                    "ids": "621,479,272,276,152,629,650,663,689,690",
                }
            )
            .with_headers(
                **{
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0",
                    "sec-ch-ua": '"Chromium";v="134", "Not:A-Brand";v="24", "Microsoft Edge";v="134"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"Windows"',
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
        ),
    ]


if __name__ == "__main__":
    TestCaseBdfy().test_start()
